Made  package for it
eggnaut/EggEngine pull request #4
Opened 2023-01-14 08:03 UTC by AjayAntoIsDev

just run pip install . to install the package
(Make a issue if anything goes wrong I will try to help)

2023-01-14 16:55 UTC, eggnaut commented
Hi! Thanks for making the package files. Unfortunately, I have no idea about creating Python packages, so I'll have to educate myself on them (Youtube... LOL). I've seen your fork and it looks good, however for me to merge the branches, I need to understand the files. I'll get back to you when I'm ready to create a Python package, thank you!

2023-01-14 17:15 UTC, eggnaut requested changes

2023-01-14 17:15 UTC, eggnaut commented on EggEngine.egg-info/PKG-INFO
> +Author: EggNaut
Author: eggnaut

2023-01-14 17:15 UTC, eggnaut commented on EggEngine.egg-info/requires.txt
> +setuptools
pygame is also a module that EggEngine uses for EggEngine.image

2023-01-15 03:36 UTC, AjayAntoIsDev commented on EggEngine.egg-info/PKG-INFO
> +Author: EggNaut
👍

2023-01-15 03:37 UTC, AjayAntoIsDev commented on EggEngine.egg-info/requires.txt
> +setuptools
You have to change it in setup.py

2023-01-15 03:38 UTC, eggnaut commented on EggEngine.egg-info/requires.txt
> +setuptools
okay got it, thanks!

2023-01-15 03:39 UTC, eggnaut approved these changes

2023-01-15 03:42 UTC, AjayAntoIsDev commented
Oops i accidentally deleted the changes

2023-01-15 03:43 UTC, eggnaut commented
Oh thats fine lol, you might be able to recover them I'm not sure.

2023-01-15 03:45 UTC, AjayAntoIsDev commented
Yea i have the files in my local machine

2023-01-15 03:45 UTC, eggnaut commented
Oh okay thats good

2023-01-15 03:47 UTC, AjayAntoIsDev commented
I will make a new pull request

2023-01-15 03:49 UTC, eggnaut commented
I re-opened this PR, you can continue here.

2023-01-15 03:50 UTC, eggnaut approved these changes

2023-01-15 03:53 UTC, AjayAntoIsDev commented
You can merge these changes if you want to

2023-01-15 03:55 UTC, eggnaut commented
> You can merge these changes if you want to

Will do when I'm ready, thank you for all your help!

2023-01-15 03:57 UTC, closed without merging

2023-01-15 03:58 UTC, AjayAntoIsDev commented
👌